In [5]:
import numpy as np

In [6]:
a = np.arange(15).reshape(3, 5)

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [10]:
a.dtype.name

'int64'

In [11]:
a.itemsize

8

In [12]:
a.size

15

In [13]:
type(a)

numpy.ndarray

In [14]:
b = np.array([6, 7, 8])

In [15]:
b

array([6, 7, 8])

In [16]:
type(b)

numpy.ndarray

In [19]:
b.size

3

In [20]:
c = np.array([1.1, 2.2, 3.3, 4.4])

In [21]:
c

array([ 1.1,  2.2,  3.3,  4.4])

In [22]:
c.dtype # Notice the difference between the int64 and float64

dtype('float64')

In [23]:
d = np.array( [ [1, 2], 
               [3, 4] ] )

In [24]:
d

array([[1, 2],
       [3, 4]])

In [26]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [27]:
print(d)

[[1 2]
 [3 4]]


In [28]:
print(c)

[ 1.1  2.2  3.3  4.4]
